name: Cron Job

on:
  schedule:
    - cron: '0 0 * * *'
  issues:
    types: [closed]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm run start

      - name: Add and commit changes
        run: |
          git config --global user.email "wwzgxsyf@gmail.com"
          git config --global user.name "wwzgxsyf"
          git add .
          git commit -m "update info"

      - name: Push changes
        uses: ad-m/github-push-action@74d8e0b6f0b86b61232a9b3a28b45bf8a5593532
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
